name: Publish Package

on:
  push:
    branches: ["main", "development"]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Verify integrity
        run: npm audit signatures
      - name: Build
        run: npm run build
      - name: Display
        run: echo ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        env:
          SERVICE_ACCOUNT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}